#!/bin/bash
verify() {
	git show-ref --verify --quiet refs/heads/develop

	if [ $? -eq 1 ] ; then
		echo "Branch Develop will be created"
		git checkout -B develop
	else
		echo "Branch Develop already exists"
	fi	

	git config credential.helper cache && git config credential.helper 'cache --timeout=30000000'
}


start() {
	if [ -z "$1" ]
	  then
	    echo "The issue branch name must be informed. Use zf start <issue>"
	    exit 1
	fi
	verify
	git fetch && git checkout develop
	git checkout -B issue/$1
}

push() {
	if [ -z "$1" ] || [ -z "$2" ] ; then
	    echo "The issue branch name and the commit message must be informed. Use zf push <issue> <text>"
	    exit 1
	fi
	git add -A .
	
	message=$(echo "$@")
    
    #echo "$message"
	git commit -m "$message"
	git push origin issue/$1
}

switch() {
	if [ -z "$1" ]
	  then
	    echo "The branch name must be informed. Use zf switch <issue>"
	    exit 1
	fi
	git fetch && git checkout issue/$1
}

merge() {
	if [ -z "$1" ] ; then
	    echo "The branch name to merge must be informed. Use zf merge <issue>"
	    exit 1
	fi
	git checkout develop
	git merge issue/$1
	git push origin develop
	git fetch && git checkout develop
	git pull origin develop
	echo "Your branch was merged to develop. You are now on develop"
}

release() {
	if [ -z "$1" ] || [ -z "$2" ] ; then
	    echo "The tag name and description be informed. Use zf release <tag_name> <tag_description>"
	    exit 1
	fi
	git fetch && git checkout develop
	git checkout master
	git merge develop
	git push origin master
	message=$(echo "$@")
	git tag -a $1 -m "$message"
	git push --tags
	git fetch && git checkout master
	git branch -D develop
	git checkout -B develop
	echo "Summary: "
	echo "-- Branch develop was merged into master"
	echo "-- A tag was pushed with name $1"
	echo "-- The branch Develop was recreated based on master"
	echo "-- You are now on develop"
}

pull() {
	if [ -z "$1" ]
	  then
	    echo "The issue branch name must be informed. Use zf pull <issue>"
	    exit 1
	fi
	git pull origin issue/$2
}

$@


